### ISSUE TITLE
Master task list

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Prototype#1]
**Basic Foundation:**
- [x] Base solutions created
- [x] Sample OWIN/AspNet5 app running
- [x] Glimpse base services and basic middleware registered 
- [x] Integrate with new core DI infrastructure 
- [x] Discovering types that implement given interfaces (basic extension model) - **IDiscoverableCollection** 
- [x] Glimpse tapping beginning and end of request in OWIN/AspNet5 samples - **IRequestRuntime**
- [x] Glimpse serving resources in OWIN/AspNet5 samples - **IRequestHandler**
- [x] Sample AspNet5 app where client server is different app to agent
- [x] Basic message publishing and subscription (**IMessage**) - **IMessageBus**
- [x] Basic remote message publishing from agent to server - **IMessagePublisher**
    - Using normal HTTP request per message - **RemoteHttpMessagePublisher**
    - Using Socket connection - **RemoteStreamMessagePublisher**
- [x] More advanced message publishing and subscription 
    - Agent side with typed objects (**IMessage**) - **IMessageAgentBus**
    - Server side with topic objects (**IMessageEnvelope**) - **IMessageServerBus**
- [x] Allow filtering/agregation/etc of objects in agent message bus - **IMessageAgentBus**
- [x] Allow filtering/agregation/etc of messages on server message bus - **IMessageServerBus**
- [x] Get messages from the server to the browser client - **IMessageClientPublisher**
- [x] Publish context data with each message - **IContextData<T>**
- [x] Allow Agent to ignore requests - **IIgnoredRequestPolicy**
    - [x] Default Policies - Uri, Content Type and Status Code 
    - [x] Allow user to replace Default (reflection based) provider with Fixed Set provider
- [x] Allow runtime to only allow authorised requests - **IRequestAuthorizer**
    - [x] Default Policies - Local only
    - [x] Allow user to replace Default (reflection based) provider with Fixed Set provider
- [x] Switch service registrations over to using fluent interface
- [x] Allow users to override provider for the following with Fixed and Default providers
    - [x] RequestRuntime, RequestHandeler, RequestAuthorizer

**Bonus Extras**
- [x] Add Request ID & URI to start/end messages
- [ ] ~~Get registration of services being discovery based~~ *Can't really do because I can't build Discoverable collection at the point the services need to be registered easily*
- [x] Switch all message passing to be async 
- [x] Abstract out SignalR connection so its not instance specific 
    - [ ] Ensure SignalR connection retry logic is correct
- [ ] Unify aspnet/owin middleware implementations (not sure this is worth doing)

**Basic remote connectivity:**
- [x] Socket connection from Browser Agent to Server
- [x] Http connection from Browser Agent to Server
- [x] In proc "connection" from Web Agent to Server
- [x] Socket connection from Web Agent to Server
- [x] Http connection from Web Agent to Server
- [x] Socket connection from Server to Browser Client

**Basic Configuration:**
- [x] Switch over `IDiscoverableCollection` over to using Provider pattern 
- [x] Setup base config for Web Agent and Web Server

**Current Issues:**
- OWIN 
    - Compatibility is down because the default container doesn't contain an instance of **ILibraryManager**
    - Additionally SignalR on AspNet5 seems hard coded to **IApplicationBuilder**, not sure yet how to register in an OWIN context
    - Looks like the HttpClient extension methods from System.Net.Http.Formatting have not been brought across to Core50 yet
- Correlation
    - Need to work out how requests are related.
- Bus
    - Do we need a way of aborting messages and stop them going over the wire/being stored?

**Comment by nikmd23** [comment]
This issues has served its purpose, but is no longer necessary.
